version: 2.1

defaults: &defaults
  working_directory: ~/grommet-ci
  docker:
    - image: circleci/node:10

aliases:
  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules
        - ~/.cache
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}
  attach: &attach
    attach_workspace:
      at: ~/grommet-ci

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_cache
      - run: yarn --frozen-lockfile
      - <<: *persist_cache
      - persist_to_workspace:
          root: ~/grommet-ci
          paths:
            - ./
  lint:
    <<: *defaults
    steps:
      - <<: *attach
      - run:
          name: Running linter
          command: yarn lint
  jest:
    <<: *defaults
    steps:
      - <<: *attach
      - run:
          name: Running jest
          command: yarn test
  e2e:
    docker:
      - image: cypress/browsers:chrome69
    steps:
      - checkout
      - <<: *restore_cache
      - run: yarn --frozen-lockfile
      - <<: *persist_cache
      - run:
          name: Running E2E tests
          command: yarn e2e
      - store_test_results:
          path: cypress/snapshots/diff
      - store_artifacts:
          path: cypress/snapshots/diff
          destination: cypress-diff
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/grommet-ci
          paths:
            - ./
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          command: |
            git config --global user.name "Grommet Community Bot"
            git config --global user.email "grommet@hpe.com"
            yarn release-stable
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grommet-ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/grommet-ci/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  build_test:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - jest:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - e2e:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - jest
            - lint
            - build
            - e2e
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - jest
            - lint
            - build
            - e2e
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
